version: '3.0'
services:
  web:
    build: .
    container_name: web
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static:/static
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - web
  
volumes:
  static: